### ISSUE TITLE
请问这个自动签到的时间点是在哪里设置的呢？

### ISSUE THREAD

**Issue by ShirlyZhang** [yimouleng/AutoNeteaseMusic#1]
我fork的项目好像没有自动签到呢~
而且这个是每次运行就会刷满310首吗，如果是这样为啥要早晚运行两次呢
求大神解答！东西特别好！非常赞！！感谢分享！

**Comment by xiaoxiaofeixf** [comment]
> 我fork的项目好像没有自动签到呢~ 而且这个是每次运行就会刷满310首吗，如果是这样为啥要早晚运行两次呢 求大神解答！东西特别好！非常赞！！感谢分享！

我给你回答吧，他这也是克隆别人的库，因为是要防止一次没有刷歌刷完，你也可以设置只运行一次。
